/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ContentId = IDL.Text;
export const CommentId = IDL.Nat;
export const PostId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Counts = IDL.Record({
  'followers' : IDL.Nat,
  'following' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'profilePicture' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'counts' : Counts,
});
export const ContentMetadata = IDL.Record({
  'id' : ContentId,
  'title' : IDL.Text,
  'contentBlob' : ExternalBlob,
  'views' : IDL.Nat,
  'mimeType' : IDL.Text,
  'description' : IDL.Text,
  'likes' : IDL.Nat,
  'albumCoverBlob' : IDL.Opt(ExternalBlob),
  'thumbnailBlob' : IDL.Opt(ExternalBlob),
  'uploader' : IDL.Principal,
  'comments' : IDL.Nat,
  'uploadTime' : IDL.Int,
});
export const Post = IDL.Record({
  'id' : PostId,
  'media' : IDL.Opt(ExternalBlob),
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'contentId' : ContentId,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const SearchCriteria = IDL.Variant({
  'mostPopular' : IDL.Null,
  'byMimeType' : IDL.Text,
  'byUploader' : IDL.Principal,
  'recent' : IDL.Null,
});
export const Participants = IDL.Record({
  'user1' : IDL.Principal,
  'user2' : IDL.Principal,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Conversation = IDL.Record({
  'participants' : Participants,
  'messages' : IDL.Vec(Message),
});
export const ThoughtComment = IDL.Record({
  'id' : CommentId,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'postId' : PostId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([ContentId, IDL.Text], [CommentId], []),
  'addThoughtComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
  'addToQueue' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearQueue' : IDL.Func([], [], []),
  'createThought' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [PostId], []),
  'deleteComment' : IDL.Func([ContentId, CommentId], [], []),
  'deleteContent' : IDL.Func([ContentId], [], []),
  'deleteThought' : IDL.Func([PostId], [], []),
  'deleteThoughtComment' : IDL.Func([PostId, CommentId], [], []),
  'deleteUserProfile' : IDL.Func([], [], []),
  'editProfile' : IDL.Func([UserProfile], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAllContent' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ContentMetadata)],
      ['query'],
    ),
  'getAllThoughts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([ContentId], [IDL.Vec(Comment)], ['query']),
  'getContent' : IDL.Func([IDL.Text], [ContentMetadata], ['query']),
  'getContentBySearchCriteria' : IDL.Func(
      [SearchCriteria, IDL.Nat, IDL.Nat],
      [IDL.Vec(ContentMetadata)],
      ['query'],
    ),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getCounts' : IDL.Func([IDL.Principal], [IDL.Opt(Counts)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getLikesCount' : IDL.Func([ContentId], [IDL.Nat], ['query']),
  'getMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(Message))],
      ['query'],
    ),
  'getMyThoughts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPlaybackQueue' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getProfilePicture' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'getThought' : IDL.Func([PostId], [Post], ['query']),
  'getThoughtComments' : IDL.Func(
      [PostId],
      [IDL.Vec(ThoughtComment)],
      ['query'],
    ),
  'getThoughtsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasUserLikedContent' : IDL.Func(
      [ContentId, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'incrementViews' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'likeThought' : IDL.Func([PostId], [], []),
  'markMessageAsRead' : IDL.Func([Participants, IDL.Nat], [], []),
  'moveItemInQueue' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'removeFromQueue' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [Message], []),
  'toggleLike' : IDL.Func([ContentId], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'updateProfilePicture' : IDL.Func([IDL.Opt(IDL.Vec(IDL.Nat8))], [], []),
  'updateThought' : IDL.Func([PostId, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'uploadContent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ContentId = IDL.Text;
  const CommentId = IDL.Nat;
  const PostId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Counts = IDL.Record({ 'followers' : IDL.Nat, 'following' : IDL.Nat });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'profilePicture' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'counts' : Counts,
  });
  const ContentMetadata = IDL.Record({
    'id' : ContentId,
    'title' : IDL.Text,
    'contentBlob' : ExternalBlob,
    'views' : IDL.Nat,
    'mimeType' : IDL.Text,
    'description' : IDL.Text,
    'likes' : IDL.Nat,
    'albumCoverBlob' : IDL.Opt(ExternalBlob),
    'thumbnailBlob' : IDL.Opt(ExternalBlob),
    'uploader' : IDL.Principal,
    'comments' : IDL.Nat,
    'uploadTime' : IDL.Int,
  });
  const Post = IDL.Record({
    'id' : PostId,
    'media' : IDL.Opt(ExternalBlob),
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'contentId' : ContentId,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const SearchCriteria = IDL.Variant({
    'mostPopular' : IDL.Null,
    'byMimeType' : IDL.Text,
    'byUploader' : IDL.Principal,
    'recent' : IDL.Null,
  });
  const Participants = IDL.Record({
    'user1' : IDL.Principal,
    'user2' : IDL.Principal,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Conversation = IDL.Record({
    'participants' : Participants,
    'messages' : IDL.Vec(Message),
  });
  const ThoughtComment = IDL.Record({
    'id' : CommentId,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'postId' : PostId,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([ContentId, IDL.Text], [CommentId], []),
    'addThoughtComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
    'addToQueue' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearQueue' : IDL.Func([], [], []),
    'createThought' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [PostId], []),
    'deleteComment' : IDL.Func([ContentId, CommentId], [], []),
    'deleteContent' : IDL.Func([ContentId], [], []),
    'deleteThought' : IDL.Func([PostId], [], []),
    'deleteThoughtComment' : IDL.Func([PostId, CommentId], [], []),
    'deleteUserProfile' : IDL.Func([], [], []),
    'editProfile' : IDL.Func([UserProfile], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAllContent' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ContentMetadata)],
        ['query'],
      ),
    'getAllThoughts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([ContentId], [IDL.Vec(Comment)], ['query']),
    'getContent' : IDL.Func([IDL.Text], [ContentMetadata], ['query']),
    'getContentBySearchCriteria' : IDL.Func(
        [SearchCriteria, IDL.Nat, IDL.Nat],
        [IDL.Vec(ContentMetadata)],
        ['query'],
      ),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getCounts' : IDL.Func([IDL.Principal], [IDL.Opt(Counts)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getLikesCount' : IDL.Func([ContentId], [IDL.Nat], ['query']),
    'getMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(Message))],
        ['query'],
      ),
    'getMyThoughts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPlaybackQueue' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getProfilePicture' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getThought' : IDL.Func([PostId], [Post], ['query']),
    'getThoughtComments' : IDL.Func(
        [PostId],
        [IDL.Vec(ThoughtComment)],
        ['query'],
      ),
    'getThoughtsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasUserLikedContent' : IDL.Func(
        [ContentId, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'incrementViews' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'likeThought' : IDL.Func([PostId], [], []),
    'markMessageAsRead' : IDL.Func([Participants, IDL.Nat], [], []),
    'moveItemInQueue' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'removeFromQueue' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [Message], []),
    'toggleLike' : IDL.Func([ContentId], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'updateProfilePicture' : IDL.Func([IDL.Opt(IDL.Vec(IDL.Nat8))], [], []),
    'updateThought' : IDL.Func(
        [PostId, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'uploadContent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };