/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileType = IDL.Variant({
  'audioMp3' : IDL.Null,
  'audioWav' : IDL.Null,
  'videoWebM' : IDL.Null,
  'videoMP4' : IDL.Null,
  'videoMov' : IDL.Null,
});
export const ContentMetadata = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'contentBlob' : ExternalBlob,
  'views' : IDL.Nat,
  'description' : IDL.Text,
  'fileType' : FileType,
  'likes' : IDL.Nat,
  'albumCoverBlob' : IDL.Opt(ExternalBlob),
  'thumbnailBlob' : IDL.Opt(ExternalBlob),
  'uploader' : IDL.Principal,
  'comments' : IDL.Nat,
  'uploadTime' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SearchCriteria = IDL.Variant({
  'mostPopular' : IDL.Null,
  'byFileType' : FileType,
  'byUploader' : IDL.Principal,
  'recent' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllContent' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ContentMetadata)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContent' : IDL.Func([IDL.Text], [ContentMetadata], ['query']),
  'getContentBySearchCriteria' : IDL.Func(
      [SearchCriteria, IDL.Nat, IDL.Nat],
      [IDL.Vec(ContentMetadata)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementViews' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadContent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        FileType,
        ExternalBlob,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileType = IDL.Variant({
    'audioMp3' : IDL.Null,
    'audioWav' : IDL.Null,
    'videoWebM' : IDL.Null,
    'videoMP4' : IDL.Null,
    'videoMov' : IDL.Null,
  });
  const ContentMetadata = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'contentBlob' : ExternalBlob,
    'views' : IDL.Nat,
    'description' : IDL.Text,
    'fileType' : FileType,
    'likes' : IDL.Nat,
    'albumCoverBlob' : IDL.Opt(ExternalBlob),
    'thumbnailBlob' : IDL.Opt(ExternalBlob),
    'uploader' : IDL.Principal,
    'comments' : IDL.Nat,
    'uploadTime' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SearchCriteria = IDL.Variant({
    'mostPopular' : IDL.Null,
    'byFileType' : FileType,
    'byUploader' : IDL.Principal,
    'recent' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllContent' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ContentMetadata)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContent' : IDL.Func([IDL.Text], [ContentMetadata], ['query']),
    'getContentBySearchCriteria' : IDL.Func(
        [SearchCriteria, IDL.Nat, IDL.Nat],
        [IDL.Vec(ContentMetadata)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementViews' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadContent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          FileType,
          ExternalBlob,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };