/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'contentId' : ContentId,
  'text' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export type CommentId = bigint;
export type ContentId = string;
export interface ContentMetadata {
  'id' : ContentId,
  'title' : string,
  'contentBlob' : ExternalBlob,
  'views' : bigint,
  'description' : string,
  'fileType' : FileType,
  'likes' : bigint,
  'albumCoverBlob' : [] | [ExternalBlob],
  'thumbnailBlob' : [] | [ExternalBlob],
  'uploader' : Principal,
  'comments' : bigint,
  'uploadTime' : bigint,
}
export type ExternalBlob = Uint8Array;
export type FileType = { 'audioMp3' : null } |
  { 'audioWav' : null } |
  { 'videoWebM' : null } |
  { 'videoMP4' : null } |
  { 'videoMov' : null };
export type SearchCriteria = { 'mostPopular' : null } |
  { 'byFileType' : FileType } |
  { 'byUploader' : Principal } |
  { 'recent' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[ContentId, string], CommentId>,
  'addToQueue' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearQueue' : ActorMethod<[], undefined>,
  'deleteCallerUserProfile' : ActorMethod<[], undefined>,
  'deleteComment' : ActorMethod<[ContentId, CommentId], undefined>,
  'deleteContent' : ActorMethod<[string], undefined>,
  'getAllContent' : ActorMethod<[bigint, bigint], Array<ContentMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[ContentId], Array<Comment>>,
  'getContent' : ActorMethod<[string], ContentMetadata>,
  'getContentBySearchCriteria' : ActorMethod<
    [SearchCriteria, bigint, bigint],
    Array<ContentMetadata>
  >,
  'getLikesCount' : ActorMethod<[ContentId], bigint>,
  'getPlaybackQueue' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasUserLikedContent' : ActorMethod<[ContentId, Principal], boolean>,
  'incrementViews' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'moveItemInQueue' : ActorMethod<[bigint, bigint], undefined>,
  'removeFromQueue' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleLike' : ActorMethod<[ContentId], undefined>,
  'uploadContent' : ActorMethod<
    [
      string,
      string,
      string,
      FileType,
      ExternalBlob,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];